// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWx09T4hXi5p-fBwwIcWnrzB5JhcBYy4',
    appId: '1:137582746983:web:4a8b3ae3f04f9dcdbea3c2',
    messagingSenderId: '137582746983',
    projectId: 'fb-labtrack',
    authDomain: 'fb-labtrack.firebaseapp.com',
    storageBucket: 'fb-labtrack.firebasestorage.app',
    measurementId: 'G-2KG5QBEXW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXzXU5bxaxgf2TQwpQOXUEyLX9EoZZ78',
    appId: '1:137582746983:android:e65574cd42b04693bea3c2',
    messagingSenderId: '137582746983',
    projectId: 'fb-labtrack',
    storageBucket: 'fb-labtrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn_UJddQJqJEOmWOUyOS8iSmdTU3Xomhg',
    appId: '1:137582746983:ios:a2e77bf2026cb791bea3c2',
    messagingSenderId: '137582746983',
    projectId: 'fb-labtrack',
    storageBucket: 'fb-labtrack.firebasestorage.app',
    iosBundleId: 'com.example.labtrackMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn_UJddQJqJEOmWOUyOS8iSmdTU3Xomhg',
    appId: '1:137582746983:ios:a2e77bf2026cb791bea3c2',
    messagingSenderId: '137582746983',
    projectId: 'fb-labtrack',
    storageBucket: 'fb-labtrack.firebasestorage.app',
    iosBundleId: 'com.example.labtrackMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGWx09T4hXi5p-fBwwIcWnrzB5JhcBYy4',
    appId: '1:137582746983:web:18e4509df3c5421dbea3c2',
    messagingSenderId: '137582746983',
    projectId: 'fb-labtrack',
    authDomain: 'fb-labtrack.firebaseapp.com',
    storageBucket: 'fb-labtrack.firebasestorage.app',
    measurementId: 'G-SH8B768XD2',
  );
}
